version: '3.7'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - config01:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
    networks:
      elastic:
        ipv4_address: 192.x.x.2

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - config02:/usr/share/elasticsearch/config
    ports:
      - 9201:9201
    networks:
      elastic:
        ipv4_address: 192.x.x.3

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - config03:/usr/share/elasticsearch/config
    ports:
      - 9202:9202
    networks:
      elastic:
        ipv4_address: 192.x.x.4

  kibana01:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana01
    networks:
     - elastic      
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - SERVER_PUBLICBASEURL=http://192.x.x.x:5601
      - ELASTICSEARCH_HOSTS=http://es01:9200
    mem_limit: 1073741824


volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  kibanadata:
    driver: local
  config01:  # Add this volume definition
    driver: local
  config02:  # Add this volume definition
    driver: local
  config03:  # Add this volume definition
    driver: local

networks:
  elastic:
    driver: bridge
    ipam:
      config:
        - subnet: 192.x.x.0/24
          gateway: 192.x.x.1
